name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  
jobs:
  qodana-rf-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
      - name: Scan API
        uses: JetBrains/qodana-action@v2023.2
        timeout-minutes: 20
        with:
          args: --project-dir,remote-falcon-api
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  qodana-rf-api-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Validate Maven Wrapper
      run: mvn --version
      working-directory: ./remote-falcon-api
    - name: Run Tests
      run: mvn test
      working-directory: ./remote-falcon-api
    - name: Archive coverage data
      uses: actions/upload-artifact@v2
      with:
        name: maven-coverage-data
        path: ./remote-falcon-api/.qodana/code-coverage
    - name: Qodana Scan
      uses: JetBrains/qodana-action@v2023.2
      timeout-minutes: 20
      with:
        args: "-i,remote-falcon-api,--linter,jetbrains/qodana-jvm:2023.2-eap"
        pr-mode: false
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  qodana-rf-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3
      - name: Scan Web
        uses: JetBrains/qodana-action@v2023.2
        timeout-minutes: 20
        with:
          args: --project-dir,remote-falcon-web
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
