name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana-rf-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Use qodana-rf-api Config'
        run: cp qodana-rf-api.yaml qodana.yaml
      - name: 'Qodana Scan RF API'
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: |
            --source-directory,remote-falcon-api
          artifact-name: qodana-rf-api
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  qodana-rf-web:
    needs: qodana-rf-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Use qodana-rf-web Config'
        run: cp qodana-rf-web.yaml qodana.yaml
      - name: 'Qodana Scan RF Web'
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: |
            --source-directory,remote-falcon-web
          artifact-name: qodana-rf-web
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
